// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDacGO0HWKj352YADeMRdCXaK1nJX95haU',
    appId: '1:471035471443:web:d03a3f41489e1d0591c8a6',
    messagingSenderId: '471035471443',
    projectId: 'to-do-list-75d9f',
    authDomain: 'to-do-list-75d9f.firebaseapp.com',
    storageBucket: 'to-do-list-75d9f.appspot.com',
    measurementId: 'G-JLWY50309X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiHanyOpXPDZ5Cc-MAY3SGRf5W6YDC8Pw',
    appId: '1:471035471443:android:3c0923ef1a0bb1d691c8a6',
    messagingSenderId: '471035471443',
    projectId: 'to-do-list-75d9f',
    storageBucket: 'to-do-list-75d9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaU_74Ym5xZuvdfftSTcyP4BM2uWhhTvk',
    appId: '1:471035471443:ios:b4683726514c1b7f91c8a6',
    messagingSenderId: '471035471443',
    projectId: 'to-do-list-75d9f',
    storageBucket: 'to-do-list-75d9f.appspot.com',
    iosClientId: '471035471443-j3ka0610i5u3r3af1upq7fu90o2aav46.apps.googleusercontent.com',
    iosBundleId: 'com.todo.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaU_74Ym5xZuvdfftSTcyP4BM2uWhhTvk',
    appId: '1:471035471443:ios:b4683726514c1b7f91c8a6',
    messagingSenderId: '471035471443',
    projectId: 'to-do-list-75d9f',
    storageBucket: 'to-do-list-75d9f.appspot.com',
    iosClientId: '471035471443-j3ka0610i5u3r3af1upq7fu90o2aav46.apps.googleusercontent.com',
    iosBundleId: 'com.todo.toDo',
  );
}
